# Generated by Django 4.0 on 2022-04-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Programming', 'Programming'), ('DBMS', 'DBMS'), ('Oops', 'Oops'), ('Python', 'Python')], max_length=100)),
                ('question', models.TextField()),
                ('optionA', models.CharField(max_length=50)),
                ('optionB', models.CharField(max_length=50)),
                ('optionC', models.CharField(max_length=50)),
                ('optionD', models.CharField(max_length=50)),
                ('answer', models.CharField(choices=[('optionA', 'A'), ('optionB', 'B'), ('optionC', 'C'), ('optionD', 'D')], max_length=50)),
            ],
        ),
    ]
