# Generated by Django 4.0 on 2022-04-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vta', '0002_alter_uploadquestion_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadquestion',
            name='subject',
            field=models.CharField(choices=[('Programming', 'Programming'), ('dbms', 'DBMS'), ('Oops', 'Oops'), ('Python', 'Python')], max_length=100),
        ),
    ]
