# Generated by Django 4.0 on 2022-04-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vta', '0003_alter_uploadquestion_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadquestion',
            name='subject',
            field=models.CharField(choices=[('programming', 'Programming'), ('dbms', 'DBMS'), ('oops', 'Oops'), ('python', 'Python')], max_length=100),
        ),
    ]
